"""remove poster field from content

Revision ID: 5978568f7262
Revises: 99a446c9bab2
Create Date: 2025-11-04 14:09:39.536473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5978568f7262'
down_revision: Union[str, Sequence[str], None] = '99a446c9bab2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('animes_id_fkey'), 'animes', type_='foreignkey')
    op.create_foreign_key(None, 'animes', 'contents', ['id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('articles_id_fkey'), 'articles', type_='foreignkey')
    op.create_foreign_key(None, 'articles', 'contents', ['id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('books_id_fkey'), 'books', type_='foreignkey')
    op.create_foreign_key(None, 'books', 'contents', ['id'], ['id'], ondelete='CASCADE')
    op.drop_column('contents', 'poster')
    op.drop_constraint(op.f('courses_id_fkey'), 'courses', type_='foreignkey')
    op.create_foreign_key(None, 'courses', 'contents', ['id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('films_id_fkey'), 'films', type_='foreignkey')
    op.create_foreign_key(None, 'films', 'contents', ['id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('games_id_fkey'), 'games', type_='foreignkey')
    op.create_foreign_key(None, 'games', 'contents', ['id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('podcasts_id_fkey'), 'podcasts', type_='foreignkey')
    op.create_foreign_key(None, 'podcasts', 'contents', ['id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('series_id_fkey'), 'series', type_='foreignkey')
    op.create_foreign_key(None, 'series', 'contents', ['id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_tags_category_id'), table_name='tags')
    op.drop_constraint(op.f('tags_category_id_fkey'), 'tags', type_='foreignkey')
    op.drop_column('tags', 'category_id')
    op.drop_constraint(op.f('videos_id_fkey'), 'videos', type_='foreignkey')
    op.create_foreign_key(None, 'videos', 'contents', ['id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'videos', type_='foreignkey')
    op.create_foreign_key(op.f('videos_id_fkey'), 'videos', 'contents', ['id'], ['id'])
    op.add_column('tags', sa.Column('category_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('tags_category_id_fkey'), 'tags', 'content_categories', ['category_id'], ['id'])
    op.create_index(op.f('ix_tags_category_id'), 'tags', ['category_id'], unique=False)
    op.drop_constraint(None, 'series', type_='foreignkey')
    op.create_foreign_key(op.f('series_id_fkey'), 'series', 'contents', ['id'], ['id'])
    op.drop_constraint(None, 'podcasts', type_='foreignkey')
    op.create_foreign_key(op.f('podcasts_id_fkey'), 'podcasts', 'contents', ['id'], ['id'])
    op.drop_constraint(None, 'games', type_='foreignkey')
    op.create_foreign_key(op.f('games_id_fkey'), 'games', 'contents', ['id'], ['id'])
    op.drop_constraint(None, 'films', type_='foreignkey')
    op.create_foreign_key(op.f('films_id_fkey'), 'films', 'contents', ['id'], ['id'])
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.create_foreign_key(op.f('courses_id_fkey'), 'courses', 'contents', ['id'], ['id'])
    op.add_column('contents', sa.Column('poster', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.create_foreign_key(op.f('books_id_fkey'), 'books', 'contents', ['id'], ['id'])
    op.drop_constraint(None, 'articles', type_='foreignkey')
    op.create_foreign_key(op.f('articles_id_fkey'), 'articles', 'contents', ['id'], ['id'])
    op.drop_constraint(None, 'animes', type_='foreignkey')
    op.create_foreign_key(op.f('animes_id_fkey'), 'animes', 'contents', ['id'], ['id'])
    # ### end Alembic commands ###
