"""feat: new tables for model lists

Revision ID: 9750087c4156
Revises: b2c3d4e5f6a7
Create Date: 2025-11-25 13:30:19.543328

"""
from typing import Sequence, Union
from sqlalchemy.dialects import postgresql

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9750087c4156'
down_revision: Union[str, Sequence[str], None] = 'b2c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
            "CREATE TYPE watchstatus AS ENUM ('COMPLETED', 'PLANNED', 'DROPPED', 'WATCHING')"
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_content_lists',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('content_id', sa.UUID(), nullable=False),
    sa.Column('content_type', sa.Enum('media', 'games', 'literature', name='content_type'), nullable=False),
    sa.Column('status', sa.Enum('completed', 'planned', 'dropped', 'watching', 'postponed', 'read', 'reading', 'finished', 'playing', name='watch_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(content_type != 'games') OR (status IN ('finished', 'playing', 'planned', 'dropped', 'postponed'))", name='ck_games_statuses'),
    sa.CheckConstraint("(content_type != 'literature') OR (status IN ('read', 'reading', 'planned', 'dropped', 'postponed'))", name='ck_literature_statuses'),
    sa.CheckConstraint("(content_type != 'media') OR (status IN ('completed', 'planned', 'dropped', 'watching', 'postponed'))", name='ck_media_statuses'),
    sa.ForeignKeyConstraint(['content_id'], ['contents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'content_id', name='uq_user_content')
    )
    op.create_index(op.f('ix_user_content_lists_content_id'), 'user_content_lists', ['content_id'], unique=False)
    op.create_index(op.f('ix_user_content_lists_id'), 'user_content_lists', ['id'], unique=False)
    op.create_index(op.f('ix_user_content_lists_user_id'), 'user_content_lists', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_content_lists_user_id'), table_name='user_content_lists')
    op.drop_index(op.f('ix_user_content_lists_id'), table_name='user_content_lists')
    op.drop_index(op.f('ix_user_content_lists_content_id'), table_name='user_content_lists')
    op.drop_table('user_content_lists')
    # ### end Alembic commands ###

    # ЯВНОЕ УДАЛЕНИЕ ТИПА ENUM ИЗ POSTGRESQL
    op.execute("DROP TYPE watchstatus")
