"""fix_content_models_and_relationships

Revision ID: 99a446c9bab2
Revises: f47b8f2b9d3e
Create Date: 2025-11-03 01:11:22.061036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '99a446c9bab2'
down_revision: Union[str, Sequence[str], None] = 'f47b8f2b9d3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop dependent tables first
    op.drop_table('content_type_tags')
    op.drop_index(op.f('ix_content_types_id'), table_name='content_types')
    op.drop_index(op.f('ix_content_types_name'), table_name='content_types')
    op.drop_index(op.f('ix_content_types_order'), table_name='content_types')
    op.drop_table('content_types')
    op.drop_index(op.f('ix_user_progress_content_id'), table_name='user_progress')
    op.drop_index(op.f('ix_user_progress_content_type'), table_name='user_progress')
    op.drop_index(op.f('ix_user_progress_id'), table_name='user_progress')
    op.drop_index(op.f('ix_user_progress_user_id'), table_name='user_progress')
    op.drop_table('user_progress')
    op.drop_index(op.f('ix_content_statuses_name'), table_name='content_statuses')
    op.drop_table('content_statuses')
    op.drop_index(op.f('ix_age_ratings_description'), table_name='age_ratings')

    # Fix content variant tables - rename content_id to id
    content_tables = ['animes', 'articles', 'books', 'courses', 'films', 'games', 'podcasts', 'series', 'videos']

    for table in content_tables:
        # Rename content_id to id
        op.alter_column(table, 'content_id', new_column_name='id')
        # Create index on id
        op.create_index(op.f(f'ix_{table}_id'), table, ['id'], unique=False)

    op.drop_index(op.f('ix_content_categories_parent_id'), table_name='content_categories')
    op.drop_constraint(op.f('content_categories_parent_id_fkey'), 'content_categories', type_='foreignkey')
    op.drop_column('content_categories', 'parent_id')
    op.alter_column('contents', 'view_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_contents_type'), table_name='contents')
    op.create_index(op.f('ix_contents_content_type'), 'contents', ['content_type'], unique=False)
    op.drop_constraint(op.f('contents_original_author_id_fkey'), 'contents', type_='foreignkey')
    op.drop_constraint(op.f('contents_country_id_fkey'), 'contents', type_='foreignkey')
    op.drop_constraint(op.f('contents_age_rating_id_fkey'), 'contents', type_='foreignkey')
    op.drop_constraint(op.f('contents_original_language_id_fkey'), 'contents', type_='foreignkey')
    op.create_foreign_key(None, 'contents', 'age_ratings', ['age_rating_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'contents', 'authors', ['original_author_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'contents', 'countries', ['country_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(None, 'contents', 'languages', ['original_language_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('difficulty_levels', 'max_score')
    op.drop_column('difficulty_levels', 'min_score')

    op.add_column('tags', sa.Column('category_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_tags_category_id'), 'tags', ['category_id'], unique=False)
    op.create_foreign_key(None, 'tags', 'content_categories', ['category_id'], ['id'])

    # Create the ContentType enum
    contenttype_enum = sa.Enum('SERIES', 'BOOK', 'FILM', 'ANIME', 'PODCAST', 'COURSE', 'ARTICLE', 'GAME', 'VIDEO', name='contenttype')
    contenttype_enum.create(op.get_bind(), checkfirst=True)

    op.alter_column('user_ratings', 'content_type',
               existing_type=sa.VARCHAR(length=50),
               type_=contenttype_enum,
               existing_nullable=False,
               postgresql_using='content_type::contenttype')
    op.alter_column('user_ratings', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('user_ratings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Revert content variant tables - rename id back to content_id
    content_tables = ['animes', 'articles', 'books', 'courses', 'films', 'games', 'podcasts', 'series', 'videos']

    for table in content_tables:
        op.drop_index(op.f(f'ix_{table}_id'), table_name=table)
        op.alter_column(table, 'id', new_column_name='content_id')

    op.alter_column('user_ratings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('user_ratings', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('user_ratings', 'content_type',
               existing_type=sa.Enum('SERIES', 'BOOK', 'FILM', 'ANIME', 'PODCAST', 'COURSE', 'ARTICLE', 'GAME', 'VIDEO', name='contenttype'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_constraint(None, 'tags', type_='foreignkey')
    op.drop_index(op.f('ix_tags_category_id'), table_name='tags')
    op.drop_column('tags', 'category_id')

    op.add_column('difficulty_levels', sa.Column('min_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('difficulty_levels', sa.Column('max_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'contents', type_='foreignkey')
    op.drop_constraint(None, 'contents', type_='foreignkey')
    op.drop_constraint(None, 'contents', type_='foreignkey')
    op.drop_constraint(None, 'contents', type_='foreignkey')
    op.create_foreign_key(op.f('contents_original_language_id_fkey'), 'contents', 'languages', ['original_language_id'], ['id'])
    op.create_foreign_key(op.f('contents_age_rating_id_fkey'), 'contents', 'age_ratings', ['age_rating_id'], ['id'])
    op.create_foreign_key(op.f('contents_country_id_fkey'), 'contents', 'countries', ['country_id'], ['id'])
    op.create_foreign_key(op.f('contents_original_author_id_fkey'), 'contents', 'authors', ['original_author_id'], ['id'])
    op.drop_index(op.f('ix_contents_content_type'), table_name='contents')
    op.create_index(op.f('ix_contents_type'), 'contents', ['content_type'], unique=False)
    op.alter_column('contents', 'view_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('content_categories', sa.Column('parent_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('content_categories_parent_id_fkey'), 'content_categories', 'content_categories', ['parent_id'], ['id'])
    op.create_index(op.f('ix_content_categories_parent_id'), 'content_categories', ['parent_id'], unique=False)
    op.add_column('books', sa.Column('content_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.create_foreign_key(op.f('books_id_fkey'), 'books', 'contents', ['content_id'], ['id'])
    op.drop_index(op.f('ix_books_id'), table_name='books')
    op.drop_column('books', 'id')
    op.add_column('articles', sa.Column('content_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'articles', type_='foreignkey')
    op.create_foreign_key(op.f('articles_id_fkey'), 'articles', 'contents', ['content_id'], ['id'])
    op.drop_index(op.f('ix_articles_id'), table_name='articles')
    op.drop_column('articles', 'id')
    op.add_column('animes', sa.Column('content_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'animes', type_='foreignkey')
    op.create_foreign_key(op.f('animes_id_fkey'), 'animes', 'contents', ['content_id'], ['id'])
    op.drop_index(op.f('ix_animes_id'), table_name='animes')
    op.drop_column('animes', 'id')
    op.create_index(op.f('ix_age_ratings_description'), 'age_ratings', ['description'], unique=True)
    op.create_table('content_statuses',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('content_statuses_pkey'))
    )
    op.create_index(op.f('ix_content_statuses_name'), 'content_statuses', ['name'], unique=True)
    op.create_table('user_progress',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('content_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('content_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('progress_percentage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('current_position', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_completed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('last_accessed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_progress_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_progress_pkey'))
    )
    op.create_index(op.f('ix_user_progress_user_id'), 'user_progress', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_progress_id'), 'user_progress', ['id'], unique=False)
    op.create_index(op.f('ix_user_progress_content_type'), 'user_progress', ['content_type'], unique=False)
    op.create_index(op.f('ix_user_progress_content_id'), 'user_progress', ['content_id'], unique=False)
    op.create_table('content_type_tags',
    sa.Column('content_type_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tag_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['content_type_id'], ['content_types.id'], name=op.f('content_type_tags_content_type_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('content_type_tags_tag_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('content_type_id', 'tag_id', name=op.f('content_type_tags_pkey'))
    )
    op.create_table('content_types',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('content_types_pkey'))
    )
    op.create_index(op.f('ix_content_types_order'), 'content_types', ['order'], unique=False)
    op.create_index(op.f('ix_content_types_name'), 'content_types', ['name'], unique=False)
    op.create_index(op.f('ix_content_types_id'), 'content_types', ['id'], unique=False)
    # ### end Alembic commands ###
