"""users: add phone nullable

Revision ID: b72dcdb88ff2
Revises: 21b86bb8cc1f
Create Date: 2025-09-29 20:14:38.996222

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b72dcdb88ff2"
down_revision: str | Sequence[str] | None = "21b86bb8cc1f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "phone_number", existing_type=sa.VARCHAR(length=15), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "phone_number", existing_type=sa.VARCHAR(length=15), nullable=False)
    # ### end Alembic commands ###
