"""users: add phone nullable

Revision ID: c0fbb44bb5cf
Revises: b72dcdb88ff2
Create Date: 2025-09-29 20:14:57.286792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0fbb44bb5cf'
down_revision: Union[str, Sequence[str], None] = 'b72dcdb88ff2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
