"""Add user content lists with foreign keys

Revision ID: c451801ef4ed
Revises: deba6baab971
Create Date: 2025-11-13 15:08:36.678686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c451801ef4ed'
down_revision: Union[str, Sequence[str], None] = 'deba6baab971'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'user_content_lists', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'user_content_lists', 'contents', ['content_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_content_lists', type_='foreignkey')
    op.drop_constraint(None, 'user_content_lists', type_='foreignkey')
    # ### end Alembic commands ###
