"""add_all_content_and_reference_models

Revision ID: dc5657b362f0
Revises: 8fdf2d1d3642
Create Date: 2025-10-27 16:56:42.137373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc5657b362f0'
down_revision: Union[str, Sequence[str], None] = '8fdf2d1d3642'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('age_ratings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('value', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_age_ratings_description'), 'age_ratings', ['description'], unique=True)
    op.create_index(op.f('ix_age_ratings_name'), 'age_ratings', ['name'], unique=True)
    op.create_index(op.f('ix_age_ratings_value'), 'age_ratings', ['value'], unique=True)
    op.create_table('authors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.String(length=128), nullable=False),
    sa.Column('link', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_authors_full_name'), 'authors', ['full_name'], unique=True)
    op.create_table('content_categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['content_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_categories_id'), 'content_categories', ['id'], unique=False)
    op.create_index(op.f('ix_content_categories_name'), 'content_categories', ['name'], unique=True)
    op.create_index(op.f('ix_content_categories_parent_id'), 'content_categories', ['parent_id'], unique=False)
    op.create_table('content_statuses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_statuses_name'), 'content_statuses', ['name'], unique=True)
    op.create_table('countries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('code', sa.String(length=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_countries_code'), 'countries', ['code'], unique=True)
    op.create_index(op.f('ix_countries_id'), 'countries', ['id'], unique=False)
    op.create_index(op.f('ix_countries_name'), 'countries', ['name'], unique=True)
    op.create_table('difficulty_levels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('min_score', sa.Float(), nullable=False),
    sa.Column('max_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_difficulty_levels_level'), 'difficulty_levels', ['level'], unique=True)
    op.create_index(op.f('ix_difficulty_levels_name'), 'difficulty_levels', ['name'], unique=True)
    op.create_table('genres',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_genres_id'), 'genres', ['id'], unique=False)
    op.create_index(op.f('ix_genres_name'), 'genres', ['name'], unique=True)
    op.create_table('languages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('code', sa.String(length=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_languages_code'), 'languages', ['code'], unique=True)
    op.create_index(op.f('ix_languages_name'), 'languages', ['name'], unique=True)
    op.create_table('platforms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platforms_name'), 'platforms', ['name'], unique=True)
    op.create_table('contents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('release_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('short_description', sa.String(length=500), nullable=True),
    sa.Column('long_description', sa.Text(), nullable=True),
    sa.Column('tags', sa.String(length=500), nullable=True),
    sa.Column('keywords', sa.String(length=500), nullable=True),
    sa.Column('original_language_id', sa.Integer(), nullable=False),
    sa.Column('age_rating_id', sa.Integer(), nullable=False),
    sa.Column('original_author_id', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.UUID(), nullable=False),
    sa.Column('banner', sa.Text(), nullable=False),
    sa.Column('trailer', sa.Text(), nullable=True),
    sa.Column('link', sa.Text(), nullable=True),
    sa.Column('poster', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['age_rating_id'], ['age_ratings.id'], ),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.ForeignKeyConstraint(['original_author_id'], ['authors.id'], ),
    sa.ForeignKeyConstraint(['original_language_id'], ['languages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contents_age_rating_id'), 'contents', ['age_rating_id'], unique=False)
    op.create_index(op.f('ix_contents_country_id'), 'contents', ['country_id'], unique=False)
    op.create_index(op.f('ix_contents_id'), 'contents', ['id'], unique=False)
    op.create_index(op.f('ix_contents_original_author_id'), 'contents', ['original_author_id'], unique=False)
    op.create_index(op.f('ix_contents_original_language_id'), 'contents', ['original_language_id'], unique=False)
    op.create_index(op.f('ix_contents_rating'), 'contents', ['rating'], unique=False)
    op.create_index(op.f('ix_contents_release_date'), 'contents', ['release_date'], unique=False)
    op.create_index(op.f('ix_contents_title'), 'contents', ['title'], unique=False)
    op.create_index(op.f('ix_contents_type'), 'contents', ['type'], unique=False)
    op.create_table('user_progress',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('content_id', sa.UUID(), nullable=False),
    sa.Column('content_type', sa.String(length=50), nullable=False),
    sa.Column('progress_percentage', sa.Float(), nullable=False),
    sa.Column('current_position', sa.Integer(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_accessed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_progress_content_id'), 'user_progress', ['content_id'], unique=False)
    op.create_index(op.f('ix_user_progress_content_type'), 'user_progress', ['content_type'], unique=False)
    op.create_index(op.f('ix_user_progress_id'), 'user_progress', ['id'], unique=False)
    op.create_index(op.f('ix_user_progress_user_id'), 'user_progress', ['user_id'], unique=False)
    op.create_table('user_ratings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('content_id', sa.UUID(), nullable=False),
    sa.Column('content_type', sa.String(length=50), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('review', sa.String(length=1000), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_ratings_content_id'), 'user_ratings', ['content_id'], unique=False)
    op.create_index(op.f('ix_user_ratings_content_type'), 'user_ratings', ['content_type'], unique=False)
    op.create_index(op.f('ix_user_ratings_id'), 'user_ratings', ['id'], unique=False)
    op.create_index(op.f('ix_user_ratings_rating'), 'user_ratings', ['rating'], unique=False)
    op.create_index(op.f('ix_user_ratings_user_id'), 'user_ratings', ['user_id'], unique=False)
    op.create_table('animes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('total_episodes', sa.Integer(), nullable=True),
    sa.Column('seasons', sa.Integer(), nullable=True),
    sa.Column('is_ongoing', sa.Boolean(), nullable=False),
    sa.Column('studio', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['contents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('articles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('reading_time_minutes', sa.Integer(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['contents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('books',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pages', sa.Integer(), nullable=True),
    sa.Column('isbn', sa.String(length=20), nullable=True),
    sa.Column('edition', sa.String(length=50), nullable=True),
    sa.Column('publisher', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['contents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_books_isbn'), 'books', ['isbn'], unique=True)
    op.create_table('content_audio_languages',
    sa.Column('content_id', sa.UUID(), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['contents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('content_id', 'language_id')
    )
    op.create_table('content_genres',
    sa.Column('content_id', sa.UUID(), nullable=False),
    sa.Column('genre_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['contents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('content_id', 'genre_id')
    )
    op.create_table('content_subtitle_languages',
    sa.Column('content_id', sa.UUID(), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['contents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('content_id', 'language_id')
    )
    op.create_table('content_tags',
    sa.Column('content_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['contents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('content_id', 'tag_id')
    )
    op.create_table('courses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('total_lessons', sa.Integer(), nullable=True),
    sa.Column('total_duration_hours', sa.Float(), nullable=True),
    sa.Column('difficulty_level', sa.String(length=20), nullable=True),
    sa.Column('instructor', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['contents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('films',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('director', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['contents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('games',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('developer', sa.String(length=100), nullable=True),
    sa.Column('publisher', sa.String(length=100), nullable=True),
    sa.Column('genre', sa.String(length=50), nullable=True),
    sa.Column('is_multiplayer', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['contents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('podcasts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('total_episodes', sa.Integer(), nullable=True),
    sa.Column('average_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('host', sa.String(length=100), nullable=True),
    sa.Column('is_ongoing', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['contents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('series',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('total_episodes', sa.Integer(), nullable=True),
    sa.Column('current_episode', sa.Integer(), nullable=True),
    sa.Column('season', sa.Integer(), nullable=True),
    sa.Column('is_ongoing', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['contents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('videos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('creator', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['contents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('videos')
    op.drop_table('series')
    op.drop_table('podcasts')
    op.drop_table('games')
    op.drop_table('films')
    op.drop_table('courses')
    op.drop_table('content_tags')
    op.drop_table('content_subtitle_languages')
    op.drop_table('content_genres')
    op.drop_table('content_audio_languages')
    op.drop_index(op.f('ix_books_isbn'), table_name='books')
    op.drop_table('books')
    op.drop_table('articles')
    op.drop_table('animes')
    op.drop_index(op.f('ix_user_ratings_user_id'), table_name='user_ratings')
    op.drop_index(op.f('ix_user_ratings_rating'), table_name='user_ratings')
    op.drop_index(op.f('ix_user_ratings_id'), table_name='user_ratings')
    op.drop_index(op.f('ix_user_ratings_content_type'), table_name='user_ratings')
    op.drop_index(op.f('ix_user_ratings_content_id'), table_name='user_ratings')
    op.drop_table('user_ratings')
    op.drop_index(op.f('ix_user_progress_user_id'), table_name='user_progress')
    op.drop_index(op.f('ix_user_progress_id'), table_name='user_progress')
    op.drop_index(op.f('ix_user_progress_content_type'), table_name='user_progress')
    op.drop_index(op.f('ix_user_progress_content_id'), table_name='user_progress')
    op.drop_table('user_progress')
    op.drop_index(op.f('ix_contents_type'), table_name='contents')
    op.drop_index(op.f('ix_contents_title'), table_name='contents')
    op.drop_index(op.f('ix_contents_release_date'), table_name='contents')
    op.drop_index(op.f('ix_contents_rating'), table_name='contents')
    op.drop_index(op.f('ix_contents_original_language_id'), table_name='contents')
    op.drop_index(op.f('ix_contents_original_author_id'), table_name='contents')
    op.drop_index(op.f('ix_contents_id'), table_name='contents')
    op.drop_index(op.f('ix_contents_country_id'), table_name='contents')
    op.drop_index(op.f('ix_contents_age_rating_id'), table_name='contents')
    op.drop_table('contents')
    op.drop_index(op.f('ix_platforms_name'), table_name='platforms')
    op.drop_table('platforms')
    op.drop_index(op.f('ix_languages_name'), table_name='languages')
    op.drop_index(op.f('ix_languages_code'), table_name='languages')
    op.drop_table('languages')
    op.drop_index(op.f('ix_genres_name'), table_name='genres')
    op.drop_index(op.f('ix_genres_id'), table_name='genres')
    op.drop_table('genres')
    op.drop_index(op.f('ix_difficulty_levels_name'), table_name='difficulty_levels')
    op.drop_index(op.f('ix_difficulty_levels_level'), table_name='difficulty_levels')
    op.drop_table('difficulty_levels')
    op.drop_index(op.f('ix_countries_name'), table_name='countries')
    op.drop_index(op.f('ix_countries_id'), table_name='countries')
    op.drop_index(op.f('ix_countries_code'), table_name='countries')
    op.drop_table('countries')
    op.drop_index(op.f('ix_content_statuses_name'), table_name='content_statuses')
    op.drop_table('content_statuses')
    op.drop_index(op.f('ix_content_categories_parent_id'), table_name='content_categories')
    op.drop_index(op.f('ix_content_categories_name'), table_name='content_categories')
    op.drop_index(op.f('ix_content_categories_id'), table_name='content_categories')
    op.drop_table('content_categories')
    op.drop_index(op.f('ix_authors_full_name'), table_name='authors')
    op.drop_table('authors')
    op.drop_index(op.f('ix_age_ratings_value'), table_name='age_ratings')
    op.drop_index(op.f('ix_age_ratings_name'), table_name='age_ratings')
    op.drop_index(op.f('ix_age_ratings_description'), table_name='age_ratings')
    op.drop_table('age_ratings')
    # ### end Alembic commands ###
