"""Add user content lists table

Revision ID: deba6baab971
Revises: fa274471e8e8
Create Date: 2025-11-12 17:47:08.524184

"""
from typing import Sequence, Union
from sqlalchemy.dialects import postgresql

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'deba6baab971'
down_revision: Union[str, Sequence[str], None] = 'fa274471e8e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
            "CREATE TYPE watchstatus AS ENUM ('COMPLETED', 'PLANNED', 'DROPPED', 'WATCHING')"
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_content_lists',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('content_id', sa.UUID(), nullable=False),
        # Используем созданный выше тип ENUM
        sa.Column('status', postgresql.ENUM(name='watchstatus', create_type=False), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id', 'content_id', name='uq_user_content')
    )
    op.create_index(op.f('ix_user_content_lists_content_id'), 'user_content_lists', ['content_id'], unique=False)
    op.create_index(op.f('ix_user_content_lists_id'), 'user_content_lists', ['id'], unique=False)
    op.create_index(op.f('ix_user_content_lists_user_id'), 'user_content_lists', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_content_lists_user_id'), table_name='user_content_lists')
    op.drop_index(op.f('ix_user_content_lists_id'), table_name='user_content_lists')
    op.drop_index(op.f('ix_user_content_lists_content_id'), table_name='user_content_lists')
    op.drop_table('user_content_lists')
    # ### end Alembic commands ###

    # ЯВНОЕ УДАЛЕНИЕ ТИПА ENUM ИЗ POSTGRESQL
    op.execute("DROP TYPE watchstatus")
