"""make banner nullable in contents table

Revision ID: fa274471e8e8
Revises: 5978568f7262
Create Date: 2025-11-04 15:32:24.044808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa274471e8e8'
down_revision: Union[str, Sequence[str], None] = '5978568f7262'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contents', 'banner',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contents', 'banner',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
