name: Lint and Type Check

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev
      - main

jobs:
  test_lint:
    name: Run Ruff check, format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv + Python
        uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.12"
          enable-cache: true

      - name: Install dependencies
        run: uv sync --locked

      - name: Ruff (lint)
        run: uv run ruff check .

      - name: Ruff format (fail on diff)
        run: uv run ruff format --diff .

  test_mypy:
    name: Run Mypy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv + Python
        uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.12"
          enable-cache: true

      - name: Install dependencies
        run: uv sync --locked

      - name: Mypy
        run: uv run mypy src/app --explicit-package-bases --package-root src